# Generated by Django 3.1.7 on 2021-03-22 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('cat_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Post Category',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Email')),
                ('last_name', models.CharField(max_length=100, verbose_name='Email')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_image1', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image1')),
                ('pst_image2', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image2')),
                ('pst_image3', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image3')),
                ('pst_image4', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image4')),
                ('pst_image5', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image5')),
                ('pst_title', models.CharField(max_length=150, verbose_name='House type')),
                ('pst_description', models.TextField(max_length=350, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('room', models.IntegerField(verbose_name='Rooms')),
                ('bath', models.IntegerField(null=True, verbose_name='Bathrooms')),
                ('toilet', models.IntegerField(null=True, verbose_name='Toilet')),
                ('cat_id', models.ManyToManyField(to='frontend.Category', verbose_name='Offer type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
    ]
