# Generated by Django 3.1.7 on 2021-03-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210323_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='cat_id',
            new_name='category',
        ),
    ]
