# Generated by Django 3.2 on 2021-05-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_postpage_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='featured',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpage',
            name='sponsored',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
