# Generated by Django 3.2 on 2021-06-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210531_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='price',
            field=models.CharField(max_length=150, verbose_name='Price'),
        ),
    ]
