# Generated by Django 3.2 on 2021-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_postpage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
