# Generated by Django 3.2 on 2021-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='sponsored',
            field=models.BooleanField(),
        ),
    ]
